export const projects = [
  {
    name: "Mathiensen",
    mt2: "1.135",
    duration: "15 días",
    year: "2022",
    description:
      "Aplicación de Autonivelante en toda la superficie, instalación de alfombra y Piso Vinílico LVT.",
    thumbnail: "/assets/images/projects/mathiensen/thumbnail.webp",
    images: [
      "/assets/images/projects/mathiensen/mathiensen_01.webp",
      "/assets/images/projects/mathiensen/mathiensen_02.webp",
      "/assets/images/projects/mathiensen/mathiensen_03.webp",
      "/assets/images/projects/mathiensen/mathiensen_04.webp",
      "/assets/images/projects/mathiensen/mathiensen_05.webp",
      "/assets/images/projects/mathiensen/mathiensen_06.webp",
      "/assets/images/projects/mathiensen/mathiensen_07.webp",
      "/assets/images/projects/mathiensen/mathiensen_08.webp",
    ],
  },
  {
    name: "Patio Foster",
    mt2: "300",
    duration: "5 días",
    year: "2022",
    description:
      "Aplicación de Autonivelante en toda la superficie a instalar pavimentos. Instalación de Piso Vinílico.",
    thumbnail: "/assets/images/projects/patioposter/patio_poster_thumbnail.webp",
    images: [
      "/assets/images/projects/patioposter/patio_poster_01.webp",
      "/assets/images/projects/patioposter/patio_poster_02.webp",
      "/assets/images/projects/patioposter/patio_poster_03.webp",
      "/assets/images/projects/patioposter/patio_poster_04.webp",
      "/assets/images/projects/patioposter/patio_poster_05.webp",
      "/assets/images/projects/patioposter/patio_poster_06.webp",
      "/assets/images/projects/patioposter/patio_poster_07.webp",
      "/assets/images/projects/patioposter/patio_poster_08.webp",
      "/assets/images/projects/patioposter/patio_poster_09.webp",
      "/assets/images/projects/patioposter/patio_poster_10.webp",
      "/assets/images/projects/patioposter/patio_poster_11.webp",
    ],
  },
  {
    name: "Cajon del Maipo",
    mt2: "1000",
    duration: "1 día",
    year: "2022",
    description: "Aplicación de Autonivelante.",
    thumbnail:
      "/assets/images/projects/cajondelmaipo/cajon_maipo_thumbnail.webp",
    images: [
      "/assets/images/projects/cajondelmaipo/cajon_maipo_01.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_02.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_03.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_04.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_05.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_06.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_07.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_08.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_09.webp",
      "/assets/images/projects/cajondelmaipo/cajon_maipo_10.webp",
    ],
  },
  {
    name: "CMaster",
    mt2: "200",
    duration: "5 días",
    year: "2022",
    description:
      "Aplicación de Autonivelante e instalación de piso Vinílico en Rollo.",
    thumbnail: "/assets/images/projects/cmaster/cmaster_thumbnail.webp",
    images: [
      "/assets/images/projects/cmaster/cmaster_01.webp",
      "/assets/images/projects/cmaster/cmaster_02.webp",
      "/assets/images/projects/cmaster/cmaster_03.webp",
      "/assets/images/projects/cmaster/cmaster_04.webp",
      "/assets/images/projects/cmaster/cmaster_05.webp",
      "/assets/images/projects/cmaster/cmaster_06.webp",
      "/assets/images/projects/cmaster/cmaster_07.webp",
      "/assets/images/projects/cmaster/cmaster_08.webp",
      "/assets/images/projects/cmaster/cmaster_09.webp",
      "/assets/images/projects/cmaster/cmaster_10.webp",
      "/assets/images/projects/cmaster/cmaster_11.webp",
      "/assets/images/projects/cmaster/cmaster_12.webp",
      "/assets/images/projects/cmaster/cmaster_13.webp",
    ],
  },
  {
    name: "Fósforo Estudio H",
    mt2: "531",
    duration: "5 días",
    year: "2022",
    description: "Instalación de Piso Vinílico LVT.",
    thumbnail:
      "/assets/images/projects/fosforoestudio/fosforo_estudio_thumbnail.webp",
    images: [
      "/assets/images/projects/fosforoestudio/fosforo_estudio_01.webp",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_02.webp",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_03.webp",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_04.webp",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_05.webp",
      "/assets/images/projects/fosforoestudio/fosforo_estudio_06.webp",
    ],
  },
  {
    name: "Oficina Casbro",
    mt2: "150",
    duration: "5 días",
    year: "2022",
    description:
      "Aplicación de Autonivelante. Instalación de Piso Vinílico LVT e Instalación de Alfombra.",
    thumbnail: "/assets/images/projects/oficinacasbro/casbro_thumbnail.webp",
    images: [
      "/assets/images/projects/oficinacasbro/casbro_01.webp",
      "/assets/images/projects/oficinacasbro/casbro_02.webp",
      "/assets/images/projects/oficinacasbro/casbro_03.webp",
      "/assets/images/projects/oficinacasbro/casbro_04.webp",
      "/assets/images/projects/oficinacasbro/casbro_05.webp",
      "/assets/images/projects/oficinacasbro/casbro_06.webp",
      "/assets/images/projects/oficinacasbro/casbro_07.webp",
    ],
  },
  {
    name: "Pichilemu",
    mt2: "70",
    duration: "1 día",
    year: "2023",
    description: "Aplicación de Autonivelante.",
    thumbnail: "/assets/images/projects/pichilemu/pichilemu_thumbnail.webp",
    images: [
      "/assets/images/projects/pichilemu/pichilemu_01.webp",
      "/assets/images/projects/pichilemu/pichilemu_02.webp",
      "/assets/images/projects/pichilemu/pichilemu_03.webp",
      "/assets/images/projects/pichilemu/pichilemu_04.webp",
      "/assets/images/projects/pichilemu/pichilemu_05.webp",
    ],
  },
  {
    name: "San Antonio",
    mt2: "500",
    duration: "3 días",
    year: "2022",
    description: "Aplicación e Instalación de Autonivelante.",
    thumbnail: "/assets/images/projects/sanantonio/sanantonio_thumbnail.webp",
    images: [
      "/assets/images/projects/sanantonio/sanantonio_01.webp",
      "/assets/images/projects/sanantonio/sanantonio_02.webp",
      "/assets/images/projects/sanantonio/sanantonio_03.webp",
      "/assets/images/projects/sanantonio/sanantonio_04.webp",
      "/assets/images/projects/sanantonio/sanantonio_05.webp",
    ],
  },
];
